<script>
  import { matchMethod, matchEar, matchStep, matchTotalSteps, matchResults, matchConfidence, matchPhase, notchParams, sessionTimer, sessionDuration, postFeeling, postSeverity, postNote, tinnitusToday, useVoice, useUpload, uploadedFileName } from "../stores/therapy.js";
  import { isPlaying, isMicromode, records, currentMode, therapyView, onboardingComplete } from "../stores/app.js";
  import { createMatchingSession, startTherapy, stopTherapy, updateTherapyParams, loadUploadedAudio, clearUploadedAudio, startMic, stopMic } from "../audio/notch.js";
  import { getAudioContext, setMasterVolume, getAnalyserNode } from "../audio/engine.js";
  import { t } from "../stores/locale.js";
  let session,currentFreqA=0,currentFreqB=0,matchingComplete=false,matchFreqResult=null,sessionInterval=null,sessionElapsed=0,selectedCarrier="white",uploadError="",micLoading=false,fileInputEl,useNoise=false,manualFreq=4000,manualPlaying=false,manualOsc=null,manualFineMode=false,manualFineCenter=4000,spectrumAnimFrame=null;
  const bandwidths=[{id:"narrow",label:"Narrow (1/3 oct)"},{id:"medium",label:"Medium (1/2 oct)"},{id:"wide",label:"Wide (1 oct)"}];
  const depths=[{id:-3,label:"-3 dB"},{id:-6,label:"-6 dB"},{id:-12,label:"-12 dB"},{id:-20,label:"-20 dB"}];
  let dailyCheckDone=false;function answerDaily(a){tinnitusToday.set(a);dailyCheckDone=true;if(a==="no")currentMode.set("sleep");}
  let onboardingStep=0;
  const oSteps=[{title:$t.notch_onboarding_1_title,desc:$t.notch_onboarding_1_desc},{title:$t.notch_onboarding_2_title,desc:$t.notch_onboarding_2_desc},{title:$t.notch_onboarding_3_title,desc:$t.notch_onboarding_3_desc}];
  function nextO(){if(onboardingStep<2)onboardingStep++;else{onboardingComplete.set(true);matchPhase.set("method-select");}}
  function selectMethod(m){resetMatching();matchMethod.set(m);matchPhase.set(m==="manual"?"manual-match":"ear-select");}
  function resetMatching(){session=null;currentFreqA=0;currentFreqB=0;matchingComplete=false;matchFreqResult=null;matchStep.set(0);matchEar.set("left");matchResults.set({left:null,right:null,confidence:0});matchConfidence.set(0);useNoise=false;}
  function goBack(){const m={"ear-select":"method-select","manual-match":"method-select","matching":"ear-select","verification":"matching","complete":"verification","result":"complete"};if(m[$matchPhase])matchPhase.set(m[$matchPhase]);}
  function selectEar(e){matchEar.set(e);if($matchMethod==="2afc"){session=createMatchingSession();matchStep.set(0);currentFreqA=0;currentFreqB=0;matchPhase.set("matching");nextPair();}}
  function nextPair(){const p=session.getNextFreqs();if(p){currentFreqA=p.freqA;currentFreqB=p.freqB;session.playPair(p.freqA,p.freqB,useNoise);}else finishMatching();}
  function playSingleTone(f){const c=getAudioContext();const o=c.createOscillator();o.type="sine";o.frequency.value=f;const g=c.createGain();g.gain.value=0.3;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+1.5);}
  function chooseFreq(c){matchFreqResult=c;session.advance(c);matchStep.set(session.currentStep);matchConfidence.set(session.getConfidence());setTimeout(()=>nextPair(),500);}
  function finishMatching(){matchFreqResult=session.getResult();matchResults.set({left:matchFreqResult,right:null,confidence:session.getConfidence()});matchConfidence.set(session.getConfidence());notchParams.update(p=>{p.left.frequency=matchFreqResult;return p;});matchPhase.set("verification");}
  function playTestTone(f){const c=getAudioContext();if(manualOsc){try{manualOsc.stop();}catch(e){}manualOsc=null;}manualOsc=c.createOscillator();manualOsc.type="sine";manualOsc.frequency.value=f;const g=c.createGain();g.gain.value=0.3;manualOsc.connect(g);g.connect(c.destination);manualOsc.start();manualPlaying=true;}
  async function handleUpload(){const f=fileInputEl?.files?.[0];if(!f)return;uploadError="";try{await loadUploadedAudio(f);uploadedFileName.set(f.name);useUpload.set(true);}catch(e){uploadError=$t.notch_unsupported_format;useUpload.set(false);}}
  function clearUpload(){clearUploadedAudio();uploadedFileName.set("");useUpload.set(false);}
  async function toggleVoice(){if($useVoice){stopMic();useVoice.set(false);}else{micLoading=true;const ok=await startMic();useVoice.set(ok);if(!ok)uploadError=$t.notch_mic_denied;micLoading=false;}}
  function stopTestTone(){if(manualOsc){try{manualOsc.stop();}catch(e){}manualOsc=null;}manualPlaying=false;}
  function toggleManualFine(){if(!manualFineMode){manualFineCenter=manualFreq;manualFineMode=true;}else manualFineMode=false;}
  function confirmManual(){matchResults.set({left:manualFreq,right:null,confidence:3});matchConfidence.set(3);notchParams.update(p=>{p.left.frequency=manualFreq;return p;});stopTestTone();matchPhase.set("verification");}
  function verifyAccept(){matchPhase.set("complete");}function verifyRetune(){resetMatching();matchPhase.set("method-select");}
  function startSession(){const f=$notchParams.left.frequency||4000;startTherapy(f,$notchParams.left.bandwidth,$notchParams.left.depth,selectedCarrier,{useVoice:$useVoice,useUpload:$useUpload});isPlaying.set(true);sessionElapsed=0;sessionTimer.set(0);setTimeout(()=>startSpectrum(),100);sessionInterval=setInterval(()=>{sessionElapsed++;sessionTimer.set(sessionElapsed);if(sessionElapsed>=$sessionDuration*60)stopSession(true);},1000);}
  function stopSession(b){stopSpectrum();stopTherapy();isPlaying.set(false);if(sessionInterval){clearInterval(sessionInterval);sessionInterval=null;}matchPhase.set("result");}
  function emergencyStop(){stopSpectrum();stopTherapy();isPlaying.set(false);if(sessionInterval){clearInterval(sessionInterval);sessionInterval=null;}therapyView.set("match");}
  function startSpectrum(){stopSpectrum();const c=document.getElementById("spectrum-canvas");if(!c)return;const c2d=c.getContext("2d");const a=getAnalyserNode();const bl=a.frequencyBinCount;const d=new Uint8Array(bl);const w=c.width,h=c.height;function draw(){spectrumAnimFrame=requestAnimationFrame(draw);a.getByteFrequencyData(d);c2d.clearRect(0,0,w,h);const bw=w/bl;for(let i=0;i<bl;i++){const bh=(d[i]/255)*h;const o=0.3+(d[i]/255)*0.7;c2d.fillStyle="rgba(0,102,204,"+o+")";c2d.fillRect(i*bw,h-bh,Math.max(bw-0.5,1),bh);}if($notchParams.left.frequency){const sr=getAudioContext().sampleRate;const x=($notchParams.left.frequency/(sr/2))*w;c2d.strokeStyle="rgba(41,151,255,0.8)";c2d.lineWidth=2;c2d.beginPath();c2d.moveTo(x,0);c2d.lineTo(x,h);c2d.stroke();c2d.fillStyle="rgba(41,151,255,0.9)";c2d.font="11px Inter, sans-serif";c2d.fillText(Math.round($notchParams.left.frequency)+" Hz",x+4,14);}}draw();}
  function stopSpectrum(){if(spectrumAnimFrame){cancelAnimationFrame(spectrumAnimFrame);spectrumAnimFrame=null;}}
  function submitRating(){const r={date:new Date().toISOString().split("T")[0],time:new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"}),mode:"therapy",duration_min:Math.round(sessionElapsed/60),frequency:$notchParams.left.frequency,bandwidth:$notchParams.left.bandwidth,depth:$notchParams.left.depth,feeling:$postFeeling,severity_before:$postSeverity,note:$postNote||""};records.update(rs=>[...rs,r]);postFeeling.set(null);postSeverity.set(5);postNote.set("");therapyView.set("match");matchPhase.set("method-select");}
  import { onDestroy } from "svelte";onDestroy(()=>{stopSpectrum();if(sessionInterval)clearInterval(sessionInterval);stopTestTone();stopTherapy();});
</script>
<div class="nt-view">{#if !$onboardingComplete}<div class="view-panel fade-in"><h2 class="title">{oSteps[onboardingStep].title}</h2><p class="desc">{oSteps[onboardingStep].desc}</p><div class="onboarding-nav"><div class="dots">{#each oSteps as _,i}<span class="dot" class:active={i===onboardingStep}></span>{/each}</div><button class="btn-primary" onclick={nextO}>{onboardingStep<2?$t.notch_next:$t.notch_start_matching}</button></div></div>
{:else if !dailyCheckDone}<div class="daily-check fade-in"><h2 class="title">{$t.notch_tinnitus_today}</h2><div class="daily-options"><button class="btn-primary" onclick={()=>answerDaily("yes")}>{$t.notch_yes}</button><button class="btn-secondary" onclick={()=>answerDaily("mild")}>{$t.notch_mild}</button><button class="btn-secondary" onclick={()=>answerDaily("no")}>{$t.notch_no}</button></div></div>
{:else if $matchPhase==="method-select"}<div class="view-panel fade-in"><h2 class="title">{$t.notch_select_method}</h2><p class="desc">{$t.notch_method_desc}</p><div class="method-grid"><button class="method-card" onclick={()=>selectMethod("2afc")}><div class="method-name">{$t.notch_adaptive}</div><div class="method-desc">{$t.notch_adaptive_desc}</div></button><button class="method-card" onclick={()=>selectMethod("manual")}><div class="method-name">{$t.notch_manual}</div><div class="method-desc">{$t.notch_manual_desc}</div></button></div></div>
  {:else if $matchPhase==="ear-select"}<div class="view-panel fade-in"><h2 class="title">{$t.notch_select_ear}</h2><p class="desc">{$t.notch_ear_desc}</p><div class="ear-grid">{#each ["left","right","both"] as ear}<button class="ear-card" onclick={()=>selectEar(ear)}><div class="ear-name">{ear==="left"?$t.notch_left:ear==="right"?$t.notch_right:$t.notch_both}</div></button>{/each}</div><button class="back-step" onclick={goBack}>&larr; {$t.notch_back}</button></div>
{:else if $matchPhase==="matching"}<div class="view-panel fade-in"><h2 class="title">{$t.notch_freq_matching}</h2><div class="progress-info"><span class="text-body">{$t.notch_round} {$matchStep}/{$matchTotalSteps}<span class="phase-badge">{session?.phase==="coarse"?$t.notch_coarse:$t.notch_fine}</span></span><div class="progress-bar-compact"><div class="progress-fill-compact" style="width:{Math.min($matchStep/$matchTotalSteps*100,100)}%"></div></div></div><p class="desc">{$t.notch_which_sound}</p><div class="afc-grid"><button class="afc-btn" onclick={()=>chooseFreq(currentFreqA)}><span class="afc-label">{$t.notch_sound_a}</span><span class="afc-freq">{Math.round(currentFreqA)} Hz</span></button><button class="afc-btn" onclick={()=>chooseFreq(currentFreqB)}><span class="afc-label">{$t.notch_sound_b}</span><span class="afc-freq">{Math.round(currentFreqB)} Hz</span></button></div><div class="replay-row"><button class="btn-secondary replay-btn" onclick={()=>playSingleTone(currentFreqA)}>{$t.notch_sound_a}</button><button class="btn-secondary replay-btn" onclick={()=>playSingleTone(currentFreqB)}>{$t.notch_sound_b}</button></div><div class="matching-tools"><button class="chip" class:selected={useNoise} onclick={()=>useNoise=!useNoise}>{useNoise?$t.notch_narrowband:$t.notch_pure_tone}</button></div><button class="back-step" onclick={goBack}>&larr; {$t.notch_back}</button></div>
  {:else if $matchPhase==="manual-match"}<div class="view-panel fade-in"><h2 class="title">{$t.notch_manual_title}</h2><p class="desc">{manualFineMode?$t.notch_manual_desc_fine:$t.notch_manual_desc_coarse}</p><div class="manual-controls"><div class="slider-with-ticks"><input type="range" min={manualFineMode?Math.max(20,manualFineCenter-100):125} max={manualFineMode?Math.min(16000,manualFineCenter+100):12000} step={manualFineMode?1:50} bind:value={manualFreq} class="freq-slider" oninput={()=>{if(manualPlaying)playTestTone(manualFreq);}} onmousedown={()=>playTestTone(manualFreq)} onmouseup={stopTestTone} /><div class="tick-marks">{#if manualFineMode}{#each Array(21) as _,i}{@const thz=manualFreq-100+i*10}{@const pct=((thz-Math.max(20,manualFineCenter-100))/(Math.min(16000,manualFineCenter+100)-Math.max(20,manualFineCenter-100)))*100}{#if thz>=Math.max(20,manualFineCenter-100)&&thz<=Math.min(16000,manualFineCenter+100)}<span class="tick" style="left:{pct}%"><span class="tick-line"></span><span class="tick-label">{thz}</span></span>{/if}{/each}{:else}{#each [125,250,500,1000,2000,4000,6000,8000,12000] as thz}{@const pct=((thz-125)/(12000-125))*100}<span class="tick" style="left:{pct}%"><span class="tick-line"></span><span class="tick-label">{thz}</span></span>{/each}{/if}</div></div><div class="freq-display"><input type="number" min="20" max="16000" bind:value={manualFreq} class="freq-input" onchange={()=>{if(manualPlaying)playTestTone(manualFreq);}} /><span class="text-body">Hz</span></div><div class="manual-actions"><button class="btn-primary" onclick={confirmManual}>{$t.notch_confirm}</button><button class="btn-secondary" onclick={()=>playTestTone(manualFreq)}>{$t.notch_preview}</button><button class="btn-secondary" onclick={stopTestTone}>{$t.notch_stop}</button><button class="btn-utility" onclick={toggleManualFine}>{manualFineMode?$t.notch_back_coarse:$t.notch_fine_tune}</button></div></div><button class="back-step" onclick={goBack}>&larr; {$t.notch_back}</button></div>
{:else if $matchPhase==="verification"}<div class="view-panel fade-in"><h2 class="title">{$t.notch_verify_title}</h2><p class="desc">{$t.notch_verify_desc} <strong>{Math.round($notchParams.left.frequency)} Hz</strong></p><div class="verification-actions"><button class="btn-primary" onclick={verifyAccept}>{$t.notch_confirm_start}</button><button class="btn-secondary" onclick={()=>playTestTone($notchParams.left.frequency)}>{$t.notch_preview}</button><button class="btn-secondary" onclick={verifyRetune}>{$t.notch_rematch}</button></div><button class="back-step" onclick={goBack}>&larr; {$t.notch_back}</button></div>
  {:else if $matchPhase==="complete"}<div class="view-panel fade-in"><h2 class="title">{$t.notch_complete_title}</h2><div class="match-report"><div class="report-item"><span class="text-caption">{$t.notch_frequency}</span><span class="text-display-md">{Math.round($notchParams.left.frequency)} Hz</span></div><div class="report-item"><span class="text-caption">{$t.notch_confidence}</span><div class="confidence-dots">{#each Array(5) as _,i}<span class="conf-dot" class:filled={i<$matchConfidence}></span>{/each}</div></div></div><div class="session-controls"><div class="control-row"><label class="text-caption-strong" for="carrier">{$t.notch_carrier}</label><div class="chip-group">{#each ["white","pink","ambient"] as c}<button class="chip" class:selected={selectedCarrier===c} onclick={()=>selectedCarrier=c}>{c==="white"?$t.notch_white_noise:c==="pink"?$t.notch_pink_noise:$t.notch_ambient}</button>{/each}</div></div><div class="control-row"><label class="text-caption-strong">{$t.notch_upload_audio}</label><div class="chip-group"><input type="file" accept="audio/*" bind:this={fileInputEl} onchange={handleUpload} style="display:none" /><button class="chip" onclick={()=>fileInputEl?.click()}>{$t.notch_select_file}</button>{#if $useUpload}<button class="chip" onclick={clearUpload}>{$t.notch_clear}</button>{/if}</div></div><div class="control-row"><label class="text-caption-strong">{$t.notch_mic}</label><div class="chip-group"><button class="chip" class:selected={$useVoice} onclick={toggleVoice} disabled={micLoading}>{micLoading?$t.notch_requesting:$useVoice?$t.notch_mic_on:$t.notch_enable_mic}</button></div></div><div class="control-row"><label class="text-caption-strong">{$t.notch_bandwidth}</label><div class="chip-group">{#each bandwidths as bw}<button class="chip" class:selected={$notchParams.left.bandwidth===bw.id} onclick={()=>notchParams.update(p=>{p.left.bandwidth=bw.id;return p;})}>{bw.label}</button>{/each}</div></div><div class="control-row"><label class="text-caption-strong">{$t.notch_depth}</label><div class="chip-group">{#each depths as d}<button class="chip" class:selected={$notchParams.left.depth===d.id} onclick={()=>notchParams.update(p=>{p.left.depth=d.id;return p;})}>{d.label}</button>{/each}</div></div><div class="control-row"><label class="text-caption-strong">{$t.notch_duration}</label><div class="chip-group">{#each [15,30,45,60] as dur}<button class="chip" class:selected={$sessionDuration===dur} onclick={()=>sessionDuration.set(dur)}>{dur} {$t.notch_min}</button>{/each}</div></div><button class="btn-hero start-btn" onclick={startSession}>{$t.notch_start_therapy}</button><button class="btn-secondary" onclick={()=>therapyView.set("match")}>{$t.notch_skip_today}</button></div><button class="back-step" onclick={goBack}>&larr; {$t.notch_back}</button></div>
  {:else if $matchPhase==="result"}<div class="view-panel fade-in"><h2 class="title">{$t.notch_session_complete}</h2><p class="desc">{$t.notch_how_feel}</p><div class="feeling-grid">{#each [{id:"better",label:$t.notch_better},{id:"unchanged",label:$t.notch_no_change},{id:"worse",label:$t.notch_worse}] as f}<button class="feeling-btn" class:selected={$postFeeling===f.id} onclick={()=>postFeeling.set(f.id)}>{f.label}</button>{/each}</div><div class="severity-slider"><label class="text-caption-strong">{$t.notch_current_level}</label><div class="slider-row"><span class="text-fine">0 {$t.notch_quiet}</span><input type="range" min="0" max="10" step="1" bind:value={$postSeverity} class="freq-slider" /><span class="text-fine">10 {$t.notch_loud}</span></div><span class="text-display-md severity-value">{$postSeverity}</span></div><div class="note-section"><label class="text-caption-strong">{$t.notch_notes}</label><textarea bind:value={$postNote} class="note-input" placeholder={$t.notch_notes_placeholder} rows="3"></textarea></div><button class="btn-hero start-btn" onclick={submitRating} disabled={!$postFeeling}>{$t.notch_save_record}</button><button class="btn-secondary" onclick={()=>matchPhase.set("method-select")}>{$t.notch_repeat}</button><button class="back-step" onclick={goBack}>&larr; {$t.notch_back}</button><div class="privacy-note text-fine">{$t.notch_privacy}</div></div>
{/if}</div>
{#if $isPlaying}<div class="session-overlay" class:micromode={$isMicromode}><button class="btn-utility emergency-btn" onclick={emergencyStop}>{$t.notch_stop_esc}</button><div class="session-info"><span class="text-tagline session-title">{$t.notch_in_session}</span><span class="text-lead">{Math.floor(sessionElapsed/60)}:{String(sessionElapsed%60).padStart(2,"0")}</span></div><div class="spectrum-container"><div class="spectrum-header"><span class="spectrum-label">{$t.notch_real_time_spec}</span><span class="spectrum-hint">{$t.notch_notch_hint}</span></div><canvas id="spectrum-canvas" width="480" height="160"></canvas></div></div>{/if}
<style>
.nt-view{flex:1;overflow-y:auto;padding:var(--space-section)var(--space-lg);display:flex;flex-direction:column;align-items:center;}
.fade-in{animation:fadeIn .3s ease-out;}
@keyframes fadeIn{from{opacity:0;transform:translateY(8px);}to{opacity:1;transform:translateY(0);}}
.view-panel{max-width:600px;width:100%;display:flex;flex-direction:column;gap:var(--space-lg);align-items:center;text-align:center;}
.title{font-size:34px;font-weight:600;line-height:1.1;letter-spacing:-.374px;color:var(--ink);}
.desc{font-size:17px;font-weight:400;line-height:1.47;letter-spacing:-.374px;color:var(--ink-muted-80);max-width:480px;}
.method-grid,.ear-grid{display:flex;gap:var(--space-md);width:100%;}
.method-card,.ear-card{flex:1;background:var(--canvas);border:1px solid var(--hairline);border-radius:var(--radius-lg);padding:var(--space-lg);display:flex;flex-direction:column;align-items:center;gap:var(--space-sm);cursor:pointer;transition:border-color .2s;text-align:center;}
.method-card:hover,.ear-card:hover{border-color:var(--primary);}
.method-name,.ear-name{font-size:17px;font-weight:600;letter-spacing:-.374px;}
.method-desc{font-size:14px;font-weight:400;color:var(--ink-muted-48);line-height:1.43;letter-spacing:-.224px;}
.daily-check{text-align:center;display:flex;flex-direction:column;gap:var(--space-lg);align-items:center;padding-top:var(--space-section);}
.daily-options{display:flex;gap:var(--space-md);}
.progress-info{width:100%;display:flex;flex-direction:column;gap:var(--space-xs);}
.phase-badge{display:inline-block;font-size:12px;font-weight:600;color:var(--primary);background:rgba(0,102,204,.1);border-radius:var(--radius-pill);padding:2px 10px;margin-left:8px;}
.progress-bar-compact{height:4px;background:var(--hairline);border-radius:2px;overflow:hidden;}
.progress-fill-compact{height:100%;background:var(--primary);border-radius:2px;transition:width .3s;}
.afc-grid{display:flex;gap:var(--space-lg);width:100%;max-width:400px;}
.afc-btn{flex:1;background:var(--surface-pearl);border:2px solid var(--hairline);border-radius:var(--radius-lg);padding:var(--space-xl);display:flex;flex-direction:column;align-items:center;gap:var(--space-sm);cursor:pointer;transition:border-color .2s;}
.afc-btn:hover{border-color:var(--primary);background:var(--canvas);}
.afc-label{font-size:14px;font-weight:600;color:var(--ink-muted-48);letter-spacing:-.224px;}
.afc-freq{font-size:24px;font-weight:600;color:var(--ink);}
.replay-row,.matching-tools{display:flex;gap:var(--space-sm);}
.manual-controls{width:100%;display:flex;flex-direction:column;align-items:center;gap:var(--space-lg);padding:var(--space-lg)0;}
.freq-slider{width:100%;max-width:400px;height:6px;-webkit-appearance:none;appearance:none;background:var(--hairline);border-radius:3px;outline:none;}
.freq-slider::-webkit-slider-thumb{-webkit-appearance:none;width:24px;height:24px;border-radius:50%;background:var(--primary);cursor:pointer;border:3px solid var(--canvas);box-shadow:0 1px 4px rgba(0,0,0,.15);}
.freq-display{display:flex;align-items:center;gap:var(--space-xs);}
.freq-input{width:120px;padding:8px 12px;border:1px solid var(--hairline);border-radius:var(--radius-sm);text-align:center;font-size:24px;font-weight:600;background:var(--canvas);font-family:inherit;}
.freq-input:focus{outline:2px solid var(--primary-focus);outline-offset:-1px;}
.manual-actions{display:flex;gap:var(--space-sm);flex-wrap:wrap;justify-content:center;}
.verification-actions{display:flex;gap:var(--space-sm);flex-wrap:wrap;justify-content:center;}
.match-report{display:flex;gap:var(--space-xl);align-items:flex-start;}
.report-item{display:flex;flex-direction:column;align-items:center;gap:var(--space-xs);}
.confidence-dots{display:flex;gap:4px;}
.conf-dot{width:12px;height:12px;border-radius:50%;background:var(--hairline);transition:background .2s;}
.conf-dot.filled{background:var(--primary);}
.session-controls{width:100%;display:flex;flex-direction:column;gap:var(--space-md);align-items:center;}
.control-row{display:flex;flex-direction:column;gap:var(--space-xs);align-items:center;}
.chip-group{display:flex;gap:var(--space-xs);flex-wrap:wrap;justify-content:center;}
.start-btn{margin-top:var(--space-md);padding:14px 36px;}
.feeling-grid{display:flex;gap:var(--space-md);}
.feeling-btn{flex:1;padding:var(--space-lg);border:2px solid var(--hairline);border-radius:var(--radius-lg);background:var(--canvas);display:flex;flex-direction:column;align-items:center;gap:var(--space-xs);cursor:pointer;transition:border-color .2s;font-size:14px;font-weight:400;color:var(--ink);}
.feeling-btn:hover,.feeling-btn.selected{border-color:var(--primary);}
.severity-slider{width:100%;max-width:400px;display:flex;flex-direction:column;gap:var(--space-sm);align-items:center;}
.slider-row{display:flex;align-items:center;gap:var(--space-sm);width:100%;}
.severity-value{color:var(--primary);}
.note-section{width:100%;display:flex;flex-direction:column;gap:var(--space-xs);text-align:left;}
.note-input{width:100%;padding:var(--space-sm);border:1px solid var(--hairline);border-radius:var(--radius-sm);resize:vertical;background:var(--canvas);font-size:14px;font-family:inherit;}
.note-input:focus{outline:2px solid var(--primary-focus);outline-offset:-1px;}
.onboarding-nav{display:flex;flex-direction:column;align-items:center;gap:var(--space-md);margin-top:var(--space-lg);}
.dots{display:flex;gap:var(--space-xs);}
.dot{width:8px;height:8px;border-radius:50%;background:var(--hairline);transition:background .2s;}
.dot.active{background:var(--primary);}
.back-step{font-size:14px;font-weight:400;color:var(--ink-muted-48);background:none;border:none;cursor:pointer;padding:4px 0;margin-top:4px;}
.back-step:hover{color:var(--primary);}
.privacy-note{color:var(--ink-muted-48);text-align:center;margin-top:var(--space-md);}
.session-overlay{position:fixed;bottom:64px;left:0;right:0;top:96px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:var(--space-lg);background:rgba(0,0,0,.85);z-index:20;}
.session-overlay.micromode{filter:brightness(.25);}
.session-overlay.micromode:hover{filter:brightness(.5);}
.emergency-btn{font-size:14px;padding:8px 20px;background:var(--surface-tile-1);color:rgba(255,255,255,.7);border:1px solid rgba(255,255,255,.1);}
.session-title{color:var(--primary-on-dark);}
.session-info{text-align:center;color:#fff;}
.spectrum-container{width:100%;max-width:520px;display:flex;flex-direction:column;gap:6px;align-items:center;}
.spectrum-header{width:100%;display:flex;justify-content:space-between;align-items:center;padding:0 4px;}
.spectrum-label{font-size:12px;font-weight:600;color:rgba(255,255,255,.7);letter-spacing:1px;text-transform:uppercase;}
.spectrum-hint{font-size:11px;color:var(--primary-on-dark);}
#spectrum-canvas{width:100%;height:auto;border-radius:var(--radius-sm);background:rgba(0,0,0,.4);}
.slider-with-ticks{width:100%;max-width:400px;display:flex;flex-direction:column;gap:4px;}
.tick-marks{position:relative;width:100%;height:28px;margin-top:2px;}
.tick{position:absolute;top:0;transform:translateX(-50%);display:flex;flex-direction:column;align-items:center;gap:2px;}
.tick-line{width:1px;height:6px;background:var(--hairline);}
.tick-label{font-size:9px;color:var(--ink-muted-48);white-space:nowrap;}
</style>
